"""Update User model with additional fields

Revision ID: 2b588b99aad9
Revises: 
Create Date: 2024-10-27 06:31:53.218816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b588b99aad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('instagram_profile', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('niche', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('engagement_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_website', sa.String(length=200), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.drop_column('business_website')
        batch_op.drop_column('business_name')
        batch_op.drop_column('engagement_rate')
        batch_op.drop_column('followers')
        batch_op.drop_column('niche')
        batch_op.drop_column('location')
        batch_op.drop_column('instagram_profile')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
