"""Add missing attributes to User model

Revision ID: 35ade03fb51f
Revises: 4d9cebfd638c
Create Date: 2024-11-17 16:06:15.096761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35ade03fb51f'
down_revision = '4d9cebfd638c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_profile', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('engagement_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('business_website', sa.String(length=255), nullable=True))
        batch_op.drop_column('followers_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('business_website')
        batch_op.drop_column('engagement_rate')
        batch_op.drop_column('followers')
        batch_op.drop_column('instagram_profile')

    # ### end Alembic commands ###
